# Generated by Django 6.0.3 on 2026-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_user_rename_film_id_review_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
